config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'crawl' => 'home#crawl'
  get  'show'  => 'home#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'home_helper'
  $output_hash = nil
  
  def index   
  end

  def crawl
    @domain_name = params[:domain_name]
    @max_urls = params[:max_urls].to_i
    if(params[:domain_name].present? && params[:max_urls].present?)
      $output_hash = DomainService.call(@domain_name,@max_urls)
      @output = $output_hash
    else
      respond_to do |format|
        format.html { redirect_to root_path(@domain_name,@max_urls) }
      end
    end 
  end

  def show
    @key = params[:key]
    @assets = $output_hash[@key]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  # def asset_helper(url_hash,key)
  #   return url_hash[key]
  # end
end

app/views/home/_crawl.html.erb
<table class="table w-100">
  <thead>
    <tr>
      <th>SR No.</th>
      <th>URL</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <%@output.keys.each_with_index do |key,i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= key %></td>
        <td><%= link_to "Show Assets",show_path(key:key), remote:true,class:'btn btn-primary'%></td>
      </tr>
    <% end %>  
  </tbody>
</table>

app/views/home/_show.html.erb
<div class="modal-dialog modal-lg full_modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Asset List</h5>
      <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
      <div class="modal-body">
        <table class="table w-100">
          <thead>
            <tr>
              <th>SR No.</th>
              <th>Assets</th>
            </tr>
          </thead>
          <tbody>
            <%@assets.each_with_index do |asset,i| %>
              <tr>
                <td><%= i+1 %></td>
                <td><%= asset %></td>
              </tr>
            <% end %>  
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button data-dismiss="modal" class="btn btn-danger">Close</button>
      </div> 
  </div>
</div>
<style>
  .full_modal-dialog {
  width: 98% !important;
  height: 92% !important;
  min-width: 98% !important;
  min-height: 92% !important;
  max-width: 98% !important;
  max-height: 92% !important;
  padding: 0 !important;
}
</style>

app/views/home/crawl.js.erb
$('.url-list').html('<%= j render partial: "crawl" %>');
$('.loader').addClass('d-none')

app/views/home/index.html.erb
<div class='text-center mt-2'>
  <h3 style="text-center">Crawl the Domain Name and find all urls and their and static assets.</h3>
</div>
<div class="p-5">
  <%= form_tag crawl_path,id:"domain-form",class:'block p-2',remote: true, method: "post" do %>
    <div class="row">
      <div class="form-group col-4">
        <%= label_tag :domain_name %>
        <%= text_field_tag "domain_name",@domain_name,class: "form-control",placeholder:'https://poplify.com/' %>
      </div>  
      <div class="form-group col-4">
        <%= label_tag :max_urls %>
        <%= number_field_tag "max_urls",@max_urls,class: "form-control",:input_html =>{:onkeypress =>"return event.charCode >= 48 && event.charCode <= 57",  :oninput=>"javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);",:maxLength=>"4", :min=> "0",:max=> "10000"} %>
      </div>
      <div class="col-1"></div>
      <div class="col-3">
      <%= submit_tag "Submit",class: "btn btn-primary",style:'margin-top:30px;',onClick:'loader()' %>
      </div>
    </div>  
  <% end %>  
  <div class="url-list block table-responsive"></div>
  <div class="loader loader-div d-none">
    <%= image_tag 'loader-ring.gif', style: 'height: 100px;'%>
    <h2 class="ml-3 mb-0 mt-0">Loading ...</h2>
  </div>
</div>
<script>
  function loader(){
    $('.loader').removeClass('d-none')
  }
</script>
<div id="asset-modal" class="modal fade m-auto" role="dialog" data-backdrop="static" style:'width:95%'></div>

app/views/home/show.js.erb
$("#asset-modal").html("<%= j render 'show',assets: @assets %>")
$("#asset-modal").modal("show")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Poplify" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Poplify" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  </head>

  <body>
    <main role="main">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>